@startuml

entity Geolocation {
    geolocation_id : number <<generated>>
    --
    code : text
    name : text
}

Geolocation |o--o{ Geolocation

entity ResearchArea {
    research_area_id : number <<generated>>
    --
    name : text
    description : text
    --
    super_research_area_id : number <<FK>>
}

ResearchArea |o--o{ ResearchArea

entity Person {
    person_id : number <<generated>>
    --
    firstname : text
    other_name : text
    lastname : text
    orcid : text
    --
    position_id : number <<FK>>
}

entity Advisorship {
    advising_relationship_type : text
    advisor_person_id : number <<FK>>
    student_person_id : number <<FK>>
}

Person }o--o| Advisorship
Person }o--o| Advisorship

Person }o--o{ ResearchArea

entity Position {
    position_id : number <<generated>>
    --
    title : text
    type : text
    start_year : number
    end_year : number
}

Position ||--o{ Person

entity OrganisationUnit {
    organisation_unit_id : number <<generated>>
    --
    name : text
    abbreviation : text
    type : text
    ror : text
    --
    geolocation_id : number <<FK>>
    super_organisation_unit_id : number <<FK>>
}

OrganisationUnit |o--o{ Geolocation
OrganisationUnit |o--o{ OrganisationUnit


entity Document {
    document_id : number <<generated>>
    --
    title : text
    publication_year : number
    doi : text
    isbn : text
    page_start : text
    page_end : text
    volume : text
    issue : text
    --
    part_of_document_id : number <<FK>>
    publisher_organisation_unit_id : number <<FK>>
    venue_journal_id : number <<FK>>
    presented_at_event_id : number <<FK>>
}

entity Citations {
    citations_id : number <<generated>>
    --
    number : number
    source : text
    --
    document_id : number <<FK>>
}

Document }o--o{ ResearchArea
Document }o--|| Citations
Document |o--o{ Document
Document |o--o{ OrganisationUnit

entity Authorship {
    order_number : number
    corresponding_author : boolean
    display_author_name : text
    --
    person_id : number <<FK>>
    document_id : number <<FK>>
}

Person }o--o| Authorship
Document }o--|| Authorship

entity Journal {
    journal_id : number <<generated>>
    --
    title : text
    abbreviation : text
    issn : text
    --
    publisher_organisation_unit_id : number <<FK>>
}

Journal }o--o{ ResearchArea
Journal |o--o{ OrganisationUnit
Journal }o--o| Document

entity Event {
    event_id : number <<generated>>
    --
    name : text
    abbreviation : text
    start_date : datetime
    end_date : datetime
    --
    geolocation_id : number <<FK>>
}

Event }o--o{ ResearchArea
Event |o--o{ Geolocation
Document |o--o{ Event

entity Grant {
    grant_id : number <<generated>>
    --
    name : text
    identifier : text
    start_year : number
    end_year : number
    total_award_amount : text
    --
    awarded_by_organisation_unit_id : number <<FK>>
    geolocation_id : number <<FK>>
    part_of_grant_id : number <<FK>>
}

Grant }o--o{ ResearchArea
Grant |o--o{ OrganisationUnit
Grant |o--o{ Geolocation
Grant |o--o{ Grant

entity Investigatorship {
    role_type : text
    --
    person_id : number <<FK>>
    grant_id : number <<FK>>
}

Investigatorship ||--o{ Person
Investigatorship ||--o{ Grant

Document }o--o{ Grant

@enduml
